server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: 고객
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: 배송
          uri: http://localhost:8082
          predicates:
            - Path=, 
        - id: BoundedContext1319
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: BoundedContext806
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: 고객
          uri: http://고객:8080
          predicates:
            - Path=/orders/**, 
        - id: 배송
          uri: http://배송:8080
          predicates:
            - Path=, 
        - id: BoundedContext1319
          uri: http://boundedContext1319:8080
          predicates:
            - Path=, 
        - id: BoundedContext806
          uri: http://boundedContext806:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
